package com.pojo;
// Generated Jul 24, 2016 8:34:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private String courseId;
     private Teacher teacher;
     private String courseName;
     private Date startDate;
     private Date endDate;
     private Set courseEnrolls = new HashSet(0);
     private Set courseDetailses = new HashSet(0);
     private Set results = new HashSet(0);

    public Courses() {
    }

    public Courses(String courseId) {
        this.courseId = courseId;
    }

	
    public Courses(String courseId, String courseName, Date startDate) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.startDate = startDate;
    }
    public Courses(String courseId, Teacher teacher, String courseName, Date startDate, Date endDate, Set courseEnrolls, Set courseDetailses, Set results) {
       this.courseId = courseId;
       this.teacher = teacher;
       this.courseName = courseName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.courseEnrolls = courseEnrolls;
       this.courseDetailses = courseDetailses;
       this.results = results;
    }
   
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getCourseEnrolls() {
        return this.courseEnrolls;
    }
    
    public void setCourseEnrolls(Set courseEnrolls) {
        this.courseEnrolls = courseEnrolls;
    }
    public Set getCourseDetailses() {
        return this.courseDetailses;
    }
    
    public void setCourseDetailses(Set courseDetailses) {
        this.courseDetailses = courseDetailses;
    }
    public Set getResults() {
        return this.results;
    }
    
    public void setResults(Set results) {
        this.results = results;
    }




}


