package com.pojo;
// Generated Jul 24, 2016 8:34:10 PM by Hibernate Tools 4.3.1



/**
 * CourseDetails generated by hbm2java
 */
public class CourseDetails  implements java.io.Serializable {


     private Integer slNo;
     private Courses courses;
     private String weekNo;
     private String lectureNo;
     private String vedio;
     private String document;

    public CourseDetails() {
    }

    public CourseDetails(Courses courses, String weekNo, String lectureNo, String vedio, String document) {
       this.courses = courses;
       this.weekNo = weekNo;
       this.lectureNo = lectureNo;
       this.vedio = vedio;
       this.document = document;
    }
   
    public Integer getSlNo() {
        return this.slNo;
    }
    
    public void setSlNo(Integer slNo) {
        this.slNo = slNo;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public String getWeekNo() {
        return this.weekNo;
    }
    
    public void setWeekNo(String weekNo) {
        this.weekNo = weekNo;
    }
    public String getLectureNo() {
        return this.lectureNo;
    }
    
    public void setLectureNo(String lectureNo) {
        this.lectureNo = lectureNo;
    }
    public String getVedio() {
        return this.vedio;
    }
    
    public void setVedio(String vedio) {
        this.vedio = vedio;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }




}


