package com.pojo;
// Generated Jul 24, 2016 8:34:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseEnroll generated by hbm2java
 */
public class CourseEnroll  implements java.io.Serializable {


     private Integer id;
     private Courses courses;
     private Student student;
     private Date joinDate;

    public CourseEnroll() {
    }

    public CourseEnroll(Courses courses, Student student, Date joinDate) {
       this.courses = courses;
       this.student = student;
       this.joinDate = joinDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }




}


