package com.pojo;
// Generated Jul 24, 2016 8:34:10 PM by Hibernate Tools 4.3.1



/**
 * Password generated by hbm2java
 */
public class Password  implements java.io.Serializable {


     private String id;
     private String password;
     private String securityQues;
     private String answer;

    public Password() {
    }

    public Password(String id, String password, String securityQues, String answer) {
       this.id = id;
       this.password = password;
       this.securityQues = securityQues;
       this.answer = answer;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecurityQues() {
        return this.securityQues;
    }
    
    public void setSecurityQues(String securityQues) {
        this.securityQues = securityQues;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


