package com.pojo;
// Generated Jul 24, 2016 8:34:10 PM by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer roleId;
     private String userId;
     private String password;
     private String role;

    public UserRole() {
    }

	
    public UserRole(String userId) {
        this.userId = userId;
    }
    public UserRole(String userId, String password, String role) {
       this.userId = userId;
       this.password = password;
       this.role = role;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


